In [137]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import random

In [138]:
x = torch.rand([1,2,2])
print(x)

tensor([[[0.2381, 0.2836],
         [0.7001, 0.2369]]])


In [161]:
class Module_conv_bn(nn.Module):
    
    def __init__(self) -> None:
        super(Module_conv_bn, self).__init__()
        self.conv = nn.Conv2d(1, 3, kernel_size=2, padding=1, stride=1, bias=True)
        self.batch = nn.BatchNorm1d(3)
    
    def forward(self, x):
        x = self.conv(x)
        #
        mean_x = x.sum()/sum(x.size())
        std = torch.sqrt(x.var())
        print(mean_x, std)
        #
        x = self.batch(x)
        return x, self.conv.weight.data, self.conv.bias.data, self.batch.weight.data, mean_x, std

In [162]:
mod = Module_conv_bn()
res, wt_conv, bs_conv, wt_batch, mean_x, std = mod(x)

print(res)

tensor(-0.3173, grad_fn=<DivBackward0>) tensor(0.1519, grad_fn=<SqrtBackward0>)
tensor([[[ 1.2773,  1.0236,  1.0118],
         [ 1.4045,  1.1566,  1.5322],
         [ 0.9969,  1.6727,  0.8900]],

        [[-1.2427, -1.4645, -1.1827],
         [-1.0456, -0.5857, -0.7345],
         [ 0.3191,  0.0097, -1.0917]],

        [[ 0.1434,  0.0057,  0.4280],
         [-0.8222, -0.8238, -0.0815],
         [-0.8177, -1.4855, -0.4935]]], grad_fn=<NativeBatchNormBackward0>)


In [176]:
class Only_Conv(nn.Module):
    def __init__(self) -> None:
        super(Only_Conv, self).__init__()
        self.new_conv = nn.Conv2d(1, 3, kernel_size=2, padding=1, stride=1, bias=True)
        # I need to update date for that conv
        self.new_conv.weight.data = wt_conv
        self.new_conv.bias.data = bs_conv
        self.batch = nn.BatchNorm1d(3)
    def forward(self, x):
        x = self.new_conv(x)
        x = self.batch(x)
        return x

In [177]:
new_mod = Only_Conv()
res = new_mod(x)
print(res)

tensor([[[ 1.2773,  1.0236,  1.0118],
         [ 1.4045,  1.1566,  1.5322],
         [ 0.9969,  1.6727,  0.8900]],

        [[-1.2427, -1.4645, -1.1827],
         [-1.0456, -0.5857, -0.7345],
         [ 0.3191,  0.0097, -1.0917]],

        [[ 0.1434,  0.0057,  0.4280],
         [-0.8222, -0.8238, -0.0815],
         [-0.8177, -1.4855, -0.4935]]], grad_fn=<NativeBatchNormBackward0>)
